# World
WORLD_DIM = 2
FIELD_WIDTH = 800
FIELD_HEIGHT = 600
FPS = 60

# Sheep
NUM_SHEEP = 20
SHEEP_RADIUS = 4
SHEEP_MAX_SPEED = 2.0

SEPARATION_RADIUS = 15
NEIGHBOR_RADIUS = 40

SEPARATION_WEIGHT = 1.5
ALIGNMENT_WEIGHT = 1.0
COHESION_WEIGHT = 0.8
DOG_REPULSION_WEIGHT = 2.5
NOISE_WEIGHT = 0.2

# Dogs
NUM_DOGS = 2
DOG_RADIUS = 6
DOG_MAX_SPEED = 4.0
DOG_ACCEL = 0.8
DOG_REPULSION_RADIUS = 60

# Bark
BARK_MULTIPLIER = 1.5

# Episode
SUCCESS_SHEEP_RATIO = 0.8
SUCCESS_FRAMES = 60
MAX_EPISODE_STEPS = 3000
